import React from 'react'

export default function InvoicePdf() {
    return (
        <div className="invoice">
            <div className="invoice-header">
                <h1>Invoice</h1>
                <p>Date: {invoiceData.date}</p>
            </div>
            <div className="invoice-address">
                <div className="invoice-from">
                    <h2>Generated By:</h2>
                    <p>{invoiceData.generatedBy}</p>
                </div>
                <div className="invoice-to">
                    <h2>Invoice Sent To:</h2>
                    <p>{invoiceData.sentTo}</p>
                </div>
            </div>
            <div className="invoice-line-items">
                <table>
                    <thead>
                        <tr>
                            <th>Description</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        {invoiceData.lineItems.map((item, index) => (
                            <tr key={index}>
                                <td>{item.description}</td>
                                <td>${item.amount.toFixed(2)}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
            <div className="invoice-total">
                <p>Total Amount: ${calculateTotal(invoiceData.lineItems).toFixed(2)}</p>
            </div>
        </div>
    );
}

// Helper function to calculate the total amount
function calculateTotal(lineItems) {
    return lineItems.reduce((total, item) => total + item.amount, 0);
}
